version: "3"

services:
  hello:
    image: httpd
    networks:
    - web
    volumes:
    - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"

  lb:
    image: haproxy:alpine
    ports:
    - 8080:80
    volumes:
    - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    networks:
    - web

networks:
  web:
    external: true